baseurl: https://www.charlesmercieca.com/
DefaultContentLanguage: en
title: Charles Mercieca
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/avatar-icon.png
  mainSections:
    - post
    - posts
  readingTime: yes
  #rss: yes
  showRelatedPosts: yes
  socialShare: yes
  #subtitle: Build a beautiful and simple website in minutes
  useHLJS: yes
  wordCount: yes
Author:
  email: c.g.mercieca@gmail.com
  github: CharlesMercieca
  linkedin: charles-mercieca-a24647196
  twitter: Charles_Merc
menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
